services:
  - type: web
    name: strava-dashboard
    env: ruby
    plan: free
    buildCommand: "bundle install && bundle exec rake assets:precompile"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: strava_dashboard_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: STRAVA_CLIENT_ID
        sync: false
      - key: STRAVA_CLIENT_SECRET
        sync: false
      - key: STRAVA_REFRESH_TOKEN
        sync: false
      - key: STRAVA_ACCESS_TOKEN
        sync: false
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"

databases:
  - name: strava_dashboard_db
    plan: free 