services:
  - type: web
    name: strava-dashboard
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: strava_dashboard_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: STRAVA_CLIENT_ID
        sync: false
      - key: STRAVA_CLIENT_SECRET
        sync: false
      - key: STRAVA_REFRESH_TOKEN
        sync: false

databases:
  - name: strava_dashboard_db
    databaseName: strava_dashboard
    user: strava_dashboard 