services:
  - type: web
    name: strava-dashboard
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    buildFilter:
      paths:
        - bin/render-build.sh
        - Gemfile
        - Gemfile.lock
        - config/**
        - app/**
        - lib/**
        - db/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: strava_dashboard_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: STRAVA_CLIENT_ID
        sync: false
      - key: STRAVA_CLIENT_SECRET
        sync: false
      - key: STRAVA_REFRESH_TOKEN
        sync: false
      - key: STRAVA_ACCESS_TOKEN
        sync: false
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: RENDER
        value: "true"

databases:
  - name: strava_dashboard_db
    plan: free 