services:
  - type: web
    name: strava-dashboard
    env: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: strava_dashboard_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: STRAVA_CLIENT_ID
        sync: false
      - key: STRAVA_CLIENT_SECRET
        sync: false
      - key: STRAVA_REFRESH_TOKEN
        sync: false
      - key: STRAVA_ACCESS_TOKEN
        sync: false
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: RENDER
        value: "true"
    disk:
      name: strava-app-data
      mountPath: /data
      sizeGB: 1

databases:
  - name: strava_dashboard_db
    plan: free
    databaseName: strava_dashboard
    user: strava_dashboard 